version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - tools_network
    ports:
      - 80:80
    volumes:
      - nginx_conf:/etc/nginx/
      - nginx_html:/usr/share/nginx/html/
  logstash:
    image: logstash
    ports:
      - "5555:5555"
    networks:
      - tools_network
    environment:
      - LOGSTASH_URL=http://ipaddress:5555  
    volumes:
      - logstash_home:/var/logstash_home
    




volumes:
  nginx_conf:
  nginx_html:
  logstash_home:

networks:
  tools_network:
