version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - selenium-node-chrome
      - selenium-node-firefox
      - selenium-hub
    links:
      - selenium-hub:hub
    environment:
      OFFLOAD_TO_HOST: 'hub'
      OFFLOAD_TO_PORT: 4444
      SERVICE_NAME: 'selenium-hub'
      HEALTH_CHECK_PATH: '/status'
      ENFORCE_HTTPS: 'false'
    restart: always
    networks:
      - tools_network
    ports:
      - 80:80
    volumes:
      - nginx_conf:/etc/nginx/
      - nginx_html:/usr/share/nginx/html/
  jira:
    container_name: jira
    image: cptactionhank/atlassian-jira:latest
    restart: always
    networks:
      - tools_network
    ports:
      - 8080:8080
  confluence:
    container_name: confluence
    image: cptactionhank/atlassian-confluence:latest
    restart: always
    networks:
      - tools_network
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence
  database:
    container_name: postgres
    image: postgres:9.6
    restart: always
    networks:
      - tools_network
    volumes:
      - database-data:/var/lib/postgresql/data
  selenium-node-firefox:
    image: selenium/node-firefox:latest
    links:
      - selenium-hub:hub
    environment:
      HUB_PORT_4444_TCP_ADDR: 'hub'
      HUB_PORT_4444_TCP_PORT: 4444
    depends_on:
      - selenium-hub
  selenium-node-chrome:
    image: selenium/node-chrome:latest
    links:
      - selenium-hub:hub
    environment:
      HUB_PORT_4444_TCP_ADDR: 'hub'
      HUB_PORT_4444_TCP_PORT: 4444
    depends_on:
      - selenium-hub
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - '4444:4444'

volumes:
  nginx_conf:
  nginx_html:
  jira-data:
  confluence-data:
  database-data:

networks:
  tools_network:
